
# Configure a default setup of Home Assistant (frontend, api, etc)
config:
discovery:
frontend:
  javascript_version: lastest
history:
  include:
    domains:
      - light
    entities:
      - device_tracker.sm_n975f
      - device_tracker.e6853
      - device_tracker.wii
      - sensor.lumi_lumi_weather_f9d02304_humidity
      - sensor.lumi_lumi_weather_f9d02304_pressure
      - sensor.lumi_lumi_weather_f9d02304_temperature
      - sensor.tasker_sm_n975f_activity
mobile_app:
recorder:
  exclude:
    entities:
      - sun.sun
sun:
system_health:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
zone: !include zones.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
cover: !include covers.yaml
switch: !include switches.yaml
light: !include lights.yaml
input_datetime: !include input_datetime.yaml
scene: !include scenes.yaml

binary_sensor:
  - platform: workday
    country: "IT"

homeassistant:
  latitude: 45.0
  longitude: 8.0
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  packages: !include_dir_named packages

hacs:
  token: !secret github_hacs_token

http:
  base_url: !secret http_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

api:

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
    - cover
    - sensor

media_player:
  - platform: kodi
    host: 127.0.0.1

mqtt:
  broker: 127.0.0.1
  username: !secret mosquitto_username
  password: !secret mosquitto_password

transmission:
  host: 127.0.0.1
  name: Transmission Deamon
  username: !secret transmission_username
  password: !secret transmission_password

notify:
  - name: family
    platform: group
    services:
      - service: mobile_app_sm_n975f
      - service: mobile_app_e6853

# utility_meter:
#  luce_ingresso_mensile:
#    source: sensor.luce_ingresso_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  luce_sala_mensile:
#    source: sensor.luce_sala_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  luce_scala_mensile:
#    source: sensor.luce_scala_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_cucina_mensile:
#    source: sensor.tapparella_cucina_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_sala_grande_mensile:
#    source: sensor.tapparella_sala_grande_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_sala_piccola_mensile:
#    source: sensor.tapparella_sala_piccola_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_camera_mensile:
#    source: sensor.tapparella_camera_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_cameretta_mensile:
#    source: sensor.tapparella_cameretta_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0
#  tapparella_bagno_mensile:
#    source: sensor.tapparella_bagno_energia_kwh
#    cycle: monthly
#    tariffs:
#      - F0

garbage_collection:
  sensors:
  - name: "Umido"
    frequency: "weekly"
    verbose_state: true
    verbose_format: "{date}, tra {days} giorni"
    date_format: "%d %B"
    collection_days:
    - wed
    - sat
  - name: "Plastica"
    frequency: "even-weeks"
    verbose_state: true
    verbose_format: "{date}, tra {days} giorni"
    date_format: "%d %B"
    collection_days: "sat"
  - name: Vetro
    frequency: "weekly"
    verbose_state: true
    verbose_format: "{date}, tra {days} giorni"
    date_format: "%d %B"
    collection_days: "wed"
  - name: Carta
    frequency: "odd-weeks"
    verbose_state: true
    verbose_format: "{date}, tra {days} giorni"
    date_format: "%d %B"
    collection_days: "sat"
  - name: "Indifferenziato"
    frequency: "weekly"
    verbose_state: true
    verbose_format: "{date}, tra {days} giorni"
    date_format: "%d %B"
    collection_days: "sat"

# history:
#  include:
#    domains:

# warning, debug
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning
