
- platform: time_date
  display_options:
    - 'time'
    - 'date_time'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: cert_expiry
  host: !secret http_hostname
  name: Home Assistant SSL Certificate

- platform: openweathermap
  api_key: !secret openweather_api_key
  monitored_conditions:
    - temperature
    - humidity
    - pressure
    - rain

#
# Tasker integration
#

- platform: mqtt
  name: tasker_sm_n975f_activity
  state_topic: "tasker/sm_n975f/activity"

# 
# Lights
#
# Note: energy is measured in W/min, indeed the energy is converted in KWh

- platform: mqtt
  name: "Luce Ingresso - Potenza"
  unit_of_measurement: "W"
  state_topic: "shellies/shellyswitch25-693DE8/relay/0/power"
- platform: mqtt
  name: "Luce Ingresso - Energia KWh"
  state_topic: "shellies/shellyswitch25-693DE8/relay/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"

- platform: mqtt
  name: "Luce Sala 1 - Potenza"
  unit_of_measurement: "W"
  state_topic: "shellies/shellyswitch25-68732B/relay/0/power"
- platform: mqtt
  name: "Luce Sala 1 - Energia KWh"
  state_topic: "shellies/shellyswitch25-68732B/relay/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"

- platform: mqtt
  name: "Luce Sala 2 - Potenza"
  unit_of_measurement: "W"
  state_topic: "shellies/shellyswitch25-68732B/relay/1/power"
- platform: mqtt
  name: "Luce Sala 2 - Energia KWh"
  state_topic: "shellies/shellyswitch25-68732B/relay/1/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"

- platform: mqtt
  name: "Luce Scala - Potenza"
  unit_of_measurement: "W"
  state_topic: "shellies/shellyswitch25-693DE8/relay/1/power"
- platform: mqtt
  name: "Luce Scala - Energia KWh"
  state_topic: "shellies/shellyswitch25-693DE8/relay/1/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"

- platform: template
  sensors:
   luci_potenza_w:
     friendly_name: Illuminazione - Potenza
     unit_of_measurement: 'W'
     value_template: "{{
       states('sensor.luce_ingresso_potenza') | float +
       states('sensor.luce_sala_1_potenza') | float +
       states('sensor.luce_sala_2_potenza') | float +
       states('sensor.luce_scala_potenza') | float
       }}"
   luci_energia_kwh:
     friendly_name: Illuminazione - Energia KWh
     unit_of_measurement: 'KWh'
     value_template: "{{
       states('sensor.luce_ingresso_mensile_f0') | float +
       states('sensor.luce_sala_1_mensile_f0') | float +
       states('sensor.luce_sala_2_mensile_f0') | float +
       states('sensor.luce_scala_mensile_f0') | float
       }}"

#
# Window Covers
#

#- platform: mqtt
#  name: Tapparella Cucina - Potenza
#  state_topic: "shellies/shellyswitch25-69310A/roller/0/power"
#- platform: mqtt
#  name: Tapparella Cucina - Energia Wmin
#  state_topic: "shellies/shellyswitch25-69310A/roller/0/energy"
#- platform: mqtt
#  name: Shelly Tapparella Bagno - Temperatura
#  state_topic: "shellies/shellyswitch25-693395/temperature"
#- platform: statistics
#  name: Tapparella Cucina - Temperatura
#  entity_id: sensor.tapparella_cucina_temperatura
#  max_age:
#    minutes: 10


#- platform: mqtt
#  name: Shelly Tapparella Bagno - Surriscaldamento
#  state_topic: "shellies/shellyswitch25-693395/overtemperature"

- platform: mqtt
  name: Tapparella Cucina - Potenza
  state_topic: "shellies/shellyswitch25-69310A/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Cucina - Energia KWh
  state_topic: "shellies/shellyswitch25-69310A/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Cucina - Temperatura
  state_topic: "shellies/shellyswitch25-69310A/temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: Tapparella Sala (Grande) - Potenza
  state_topic: "shellies/shellyswitch25-69E5D4/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Sala (Grande) - Energia KWh
  state_topic: "shellies/shellyswitch25-69E5D4/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Sala (Grande) - Temperatura
  state_topic: "shellies/shellyswitch25-69E5D4/temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: Tapparella Sala (Piccola) - Potenza
  state_topic: "shellies/shellyswitch25-6940A2/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Sala (Piccola) - Energia KWh
  state_topic: "shellies/shellyswitch25-6940A2/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Sala (Piccola) - Temperatura
  state_topic: "shellies/shellyswitch25-6940A2/temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: Tapparella Camera - Potenza
  state_topic: "shellies/shellyswitch25-68F596/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Camera - Energia KWh
  state_topic: "shellies/shellyswitch25-68F596/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Camera - Temperatura
  state_topic: "shellies/shellyswitch25-68F596/temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: Tapparella Cameretta - Potenza
  state_topic: "shellies/shellyswitch25-69012F/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Cameretta - Energia KWh
  state_topic: "shellies/shellyswitch25-69012F/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Cameretta - Temperatura
  state_topic: "shellies/shellyswitch25-69012F/temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: Tapparella Bagno - Potenza
  state_topic: "shellies/shellyswitch25-693395/roller/0/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: Tapparella Bagno - Energia KWh
  state_topic: "shellies/shellyswitch25-693395/roller/0/energy"
  value_template: "{{ value|float / 60000 }}"
  unit_of_measurement: "KWh"
- platform: mqtt
  name: Tapparella Bagno - Temperatura
  state_topic: "shellies/shellyswitch25-693395/temperature"
  unit_of_measurement: "°C"

- platform: template
  sensors:
   tapparelle_potenza:
     friendly_name: Tapparelle - Potenza
     unit_of_measurement: 'W'
     value_template: "{{
       states('sensor.tapparella_cucina_potenza') | float +
       states('sensor.tapparella_sala_grande_potenza') | float +
       states('sensor.tapparella_sala_piccola_potenza') | float +
       states('sensor.tapparella_camera_potenza') | float +
       states('sensor.tapparella_cameretta_potenza') | float +
       states('sensor.tapparella_bagno_potenza') | float
     }}"
   tapparelle_energia_kwh:
     friendly_name: Tapparelle - Energia
     unit_of_measurement: 'KWh'
     value_template: "{{
       states('sensor.tapparella_cucina_mensile_f0') | float +
       states('sensor.tapparella_sala_grande_mensile_f0') | float +
       states('sensor.tapparella_sala_piccola_mensile_f0') | float +
       states('sensor.tapparella_camera_mensile_f0') | float +
       states('sensor.tapparella_cameretta_mensile_f0') | float +
       states('sensor.tapparella_bagno_mensile_f0') | float
     }}"

